In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
from sklearn.naive_bayes import GaussianNB
#from sklearn.model_selection import cross_val_score
import warnings
warnings.filterwarnings("ignore")

In [3]:
data=pd.read_csv("C:\Users\hello\Desktop\WineData\winequality-white.csv",delimiter = ";")
print(data)
#X = np.array(data.loc['fixed acidity':'alcohol'])
#Y = np.array(data.loc['quality'])
quality=data['quality'].values
label1=[]
for i in quality:
    if i<=5:
        label1.append("low") 
    if i==6 or i==7:
        label1.append("medium")
    if i>7:
        label1.append("high")
#print(label1)
d={'label': label1}
df = pd.DataFrame(d)
new_data=data.drop(['quality'], axis=1)
temp=[new_data,df]
final_data=pd.concat(temp,axis=1)
print(final_data)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36           20.70      0.045   
1               6.3             0.300         0.34            1.60      0.049   
2               8.1             0.280         0.40            6.90      0.050   
3               7.2             0.230         0.32            8.50      0.058   
4               7.2             0.230         0.32            8.50      0.058   
5               8.1             0.280         0.40            6.90      0.050   
6               6.2             0.320         0.16            7.00      0.045   
7               7.0             0.270         0.36           20.70      0.045   
8               6.3             0.300         0.34            1.60      0.049   
9               8.1             0.220         0.43            1.50      0.044   
10              8.1             0.270         0.41            1.45      0.033   
11              8.6         

In [4]:
#spliting the data into target and other columns as varibles
X=np.array(final_data.loc[:,'fixed acidity':'alcohol'])
y=np.array(final_data['label'])
X_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [5]:
clf=GaussianNB()
clf.fit(X_train,y_train)
predicted=clf.predict(x_test)
scores=[]
scores.append(accuracy_score(y_test,predicted))
print(scores)

[0.6581632653061225]


In [6]:
#using confusion matrix to find the accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predicted)
print(cm)

[[  1   6  28]
 [  1 181 168]
 [ 18 114 463]]


In [7]:
#from statistics import mean 
import time
from sklearn.model_selection import cross_validate
from sklearn.model_selection import ShuffleSplit
scores_test=[]
start=time.time()
for j in range(1,200):
    X=np.array(final_data.loc[:,'fixed acidity':'alcohol'])
    Y=np.array(final_data['label'])
    clf=GaussianNB()
    cv = ShuffleSplit(n_splits=25, test_size=0.2)
    accuracies = cross_validate(clf, X,Y, cv = cv)
    print(accuracies['test_score'])
    print(max(accuracies['test_score']))
    scores_test.append(max(accuracies['test_score']))
end=time.time()
elapsed=end-start
print(scores_test)
mean=sum(scores_test) / len(scores_test)
print("Maximum accuracy after shuffling the data "+str(max(scores_test)))
print("Mean accuracy is",mean)
print("Time taken is :",elapsed)

[0.66428571 0.66836735 0.64183673 0.6744898  0.67653061 0.67755102
 0.65102041 0.69387755 0.65612245 0.67959184 0.66530612 0.66530612
 0.68877551 0.66326531 0.6622449  0.66734694 0.6755102  0.65408163
 0.65510204 0.68163265 0.63163265 0.65102041 0.65816327 0.6622449
 0.70612245]
0.7061224489795919
[0.64795918 0.6744898  0.68061224 0.66326531 0.68673469 0.68877551
 0.65204082 0.67346939 0.65408163 0.65714286 0.65714286 0.6622449
 0.65816327 0.66938776 0.66734694 0.66020408 0.65918367 0.68673469
 0.67142857 0.66326531 0.66428571 0.67346939 0.65306122 0.65816327
 0.6744898 ]
0.6887755102040817
[0.6622449  0.68163265 0.64387755 0.66632653 0.68673469 0.65714286
 0.67040816 0.65306122 0.67142857 0.65612245 0.6877551  0.6744898
 0.68163265 0.6744898  0.67653061 0.66326531 0.69387755 0.66836735
 0.64081633 0.68265306 0.68469388 0.67959184 0.63265306 0.68265306
 0.65612245]
0.6938775510204082
[0.65102041 0.63673469 0.66428571 0.66428571 0.65204082 0.64897959
 0.64489796 0.67244898 0.67755102 0.

[0.63163265 0.67040816 0.66632653 0.66326531 0.64387755 0.67346939
 0.65306122 0.65       0.64693878 0.66632653 0.67755102 0.66632653
 0.65204082 0.67653061 0.68163265 0.65714286 0.69693878 0.64591837
 0.6755102  0.65612245 0.66734694 0.67755102 0.66632653 0.6755102
 0.69183673]
0.6969387755102041
[0.67346939 0.67346939 0.65510204 0.64795918 0.62959184 0.69081633
 0.63877551 0.6622449  0.67857143 0.67959184 0.65816327 0.66836735
 0.68571429 0.68979592 0.64591837 0.64693878 0.67244898 0.66632653
 0.63265306 0.65714286 0.64285714 0.66734694 0.66122449 0.67040816
 0.65714286]
0.6908163265306122
[0.64897959 0.66020408 0.6622449  0.64285714 0.66632653 0.65408163
 0.67244898 0.65918367 0.64591837 0.64285714 0.64897959 0.68367347
 0.67857143 0.63877551 0.65       0.65714286 0.66938776 0.64285714
 0.67755102 0.6744898  0.69183673 0.67244898 0.6744898  0.67346939
 0.65612245]
0.6918367346938775
[0.67755102 0.67244898 0.68979592 0.67959184 0.64591837 0.66938776
 0.64387755 0.67040816 0.64693878 

[0.63469388 0.67755102 0.65408163 0.64489796 0.64285714 0.68265306
 0.68469388 0.65408163 0.66938776 0.68061224 0.62653061 0.65510204
 0.66632653 0.67040816 0.65816327 0.66632653 0.69285714 0.66530612
 0.66530612 0.68265306 0.64897959 0.66122449 0.64285714 0.68571429
 0.64897959]
0.6928571428571428
[0.68469388 0.64183673 0.68979592 0.66326531 0.66734694 0.64387755
 0.67142857 0.63979592 0.67857143 0.6755102  0.66530612 0.68061224
 0.64285714 0.65408163 0.68163265 0.6755102  0.64387755 0.66428571
 0.6622449  0.68367347 0.65612245 0.64795918 0.67040816 0.67653061
 0.67040816]
0.689795918367347
[0.68571429 0.65102041 0.65204082 0.64489796 0.65510204 0.64183673
 0.65204082 0.65408163 0.6622449  0.65918367 0.67142857 0.65714286
 0.63469388 0.63673469 0.65204082 0.67142857 0.67142857 0.68877551
 0.6622449  0.65918367 0.6622449  0.66020408 0.66836735 0.68673469
 0.65714286]
0.6887755102040817
[0.6744898  0.67244898 0.66020408 0.67346939 0.65918367 0.66836735
 0.66734694 0.65714286 0.67040816 

[0.66734694 0.67142857 0.67857143 0.64795918 0.67857143 0.65510204
 0.65204082 0.66632653 0.66938776 0.67244898 0.68265306 0.66632653
 0.66020408 0.67142857 0.64285714 0.67959184 0.65816327 0.66122449
 0.68061224 0.65408163 0.65612245 0.67040816 0.67959184 0.66530612
 0.64387755]
0.6826530612244898
[0.66122449 0.65612245 0.64183673 0.64285714 0.68571429 0.66836735
 0.66326531 0.66938776 0.68163265 0.66020408 0.65       0.66734694
 0.66530612 0.65918367 0.64897959 0.66122449 0.65510204 0.66020408
 0.64795918 0.67040816 0.68571429 0.66530612 0.67755102 0.66632653
 0.68469388]
0.6857142857142857
[0.65918367 0.67653061 0.65612245 0.64285714 0.6744898  0.66122449
 0.65204082 0.65204082 0.65306122 0.6377551  0.65408163 0.65714286
 0.66020408 0.66428571 0.65918367 0.66530612 0.66938776 0.65306122
 0.67755102 0.66734694 0.66836735 0.67244898 0.66020408 0.66326531
 0.65408163]
0.6775510204081633
[0.65306122 0.68061224 0.67244898 0.66122449 0.65816327 0.65102041
 0.67346939 0.65612245 0.66122449

[0.64489796 0.66122449 0.6744898  0.66836735 0.65510204 0.6744898
 0.67142857 0.65306122 0.65204082 0.64081633 0.68061224 0.65
 0.66530612 0.66428571 0.63979592 0.65918367 0.67040816 0.66020408
 0.67040816 0.66632653 0.66938776 0.69795918 0.64795918 0.67346939
 0.65102041]
0.6979591836734694
[0.65918367 0.65918367 0.6622449  0.68061224 0.67244898 0.65
 0.64693878 0.66326531 0.65816327 0.65408163 0.67244898 0.64285714
 0.6622449  0.66632653 0.66938776 0.66632653 0.66836735 0.66428571
 0.67959184 0.66428571 0.66530612 0.66734694 0.6744898  0.65408163
 0.68367347]
0.6836734693877551
[0.6877551  0.66428571 0.63673469 0.6744898  0.66734694 0.65
 0.63979592 0.67959184 0.66734694 0.66020408 0.65816327 0.65918367
 0.65102041 0.67142857 0.67244898 0.65204082 0.6377551  0.66734694
 0.63469388 0.71020408 0.64897959 0.67755102 0.65918367 0.65204082
 0.66836735]
0.710204081632653
[0.67755102 0.65510204 0.65102041 0.6622449  0.66632653 0.65306122
 0.65714286 0.65918367 0.67959184 0.67653061 0.676530

[0.65204082 0.6377551  0.68673469 0.65510204 0.6755102  0.6744898
 0.67346939 0.6622449  0.67346939 0.65306122 0.64081633 0.63979592
 0.66938776 0.66020408 0.65510204 0.67755102 0.6744898  0.67244898
 0.6622449  0.65816327 0.68367347 0.67857143 0.66530612 0.66122449
 0.68877551]
0.6887755102040817
[0.66836735 0.6622449  0.66734694 0.67346939 0.64387755 0.66734694
 0.64897959 0.67857143 0.68367347 0.66020408 0.67346939 0.67244898
 0.67755102 0.64489796 0.66428571 0.65306122 0.70204082 0.66122449
 0.65816327 0.66122449 0.68265306 0.6755102  0.6755102  0.68979592
 0.66530612]
0.7020408163265306
[0.66020408 0.65204082 0.6744898  0.62653061 0.66122449 0.66122449
 0.68571429 0.65408163 0.62959184 0.68163265 0.65306122 0.65714286
 0.65510204 0.66326531 0.6744898  0.65408163 0.64591837 0.6622449
 0.64795918 0.67959184 0.6744898  0.6377551  0.68163265 0.66632653
 0.67244898]
0.6857142857142857
[0.70510204 0.67244898 0.67346939 0.6622449  0.70510204 0.67346939
 0.65714286 0.65408163 0.64693878 0

[0.65714286 0.65816327 0.65510204 0.68571429 0.68673469 0.66122449
 0.64897959 0.64183673 0.66326531 0.68367347 0.67040816 0.65
 0.66020408 0.6622449  0.6744898  0.66326531 0.64795918 0.6622449
 0.65918367 0.6744898  0.68367347 0.67653061 0.63571429 0.65612245
 0.65714286]
0.686734693877551
[0.6622449  0.69081633 0.66734694 0.66428571 0.66938776 0.67857143
 0.66530612 0.65918367 0.66326531 0.64591837 0.66428571 0.68163265
 0.67040816 0.63979592 0.66122449 0.67959184 0.63367347 0.69591837
 0.65408163 0.65306122 0.66326531 0.67857143 0.65       0.6755102
 0.66428571]
0.6959183673469388
[0.63877551 0.66938776 0.67346939 0.64795918 0.67142857 0.66122449
 0.66938776 0.66632653 0.68265306 0.6622449  0.64897959 0.64693878
 0.6744898  0.65714286 0.66326531 0.68469388 0.64795918 0.67040816
 0.66632653 0.64285714 0.6755102  0.66632653 0.6755102  0.66530612
 0.64693878]
0.6846938775510204
[0.67653061 0.67857143 0.65816327 0.64693878 0.67653061 0.66734694
 0.66632653 0.68469388 0.63469388 0.668367

[0.64897959 0.65102041 0.67653061 0.65408163 0.67040816 0.65714286
 0.65816327 0.67346939 0.68163265 0.67244898 0.68163265 0.6744898
 0.65918367 0.67244898 0.6877551  0.65306122 0.64387755 0.64897959
 0.67244898 0.67346939 0.65102041 0.66020408 0.65510204 0.66326531
 0.67244898]
0.6877551020408164
[0.6744898  0.65408163 0.66428571 0.66734694 0.65816327 0.65714286
 0.63979592 0.65612245 0.64183673 0.63469388 0.67959184 0.66122449
 0.65816327 0.6755102  0.67346939 0.68265306 0.67040816 0.64693878
 0.66122449 0.67244898 0.67653061 0.66734694 0.6755102  0.65408163
 0.66020408]
0.6826530612244898
[0.66836735 0.63877551 0.64081633 0.65306122 0.69387755 0.66632653
 0.68061224 0.66734694 0.65714286 0.6755102  0.66428571 0.6755102
 0.66938776 0.67755102 0.64285714 0.64693878 0.64081633 0.65408163
 0.65204082 0.66122449 0.64591837 0.67142857 0.65816327 0.61836735
 0.68469388]
0.6938775510204082
[0.7061224489795919, 0.6887755102040817, 0.6938775510204082, 0.6857142857142857, 0.6846938775510204, 0